/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as MetragemRouteImport } from './routes/metragem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlterarRouteImport } from './routes/alterar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetragemRoute = MetragemRouteImport.update({
  id: '/metragem',
  path: '/metragem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarRoute = AlterarRouteImport.update({
  id: '/alterar',
  path: '/alterar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/todos': typeof TodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlterarRoute: typeof AlterarRoute
  CadastroRoute: typeof CadastroRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MetragemRoute: typeof MetragemRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metragem': {
      id: '/metragem'
      path: '/metragem'
      fullPath: '/metragem'
      preLoaderRoute: typeof MetragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar': {
      id: '/alterar'
      path: '/alterar'
      fullPath: '/alterar'
      preLoaderRoute: typeof AlterarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlterarRoute: AlterarRoute,
  CadastroRoute: CadastroRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MetragemRoute: MetragemRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
